# --------------------------------------------------------------------------------------------------
#
#   Stellars Jupyterlab DS Platform 
#   Project Home: https://github.com/stellarshenson/stellars-jupyterlab-ds
#   This file adds GPU support to compose.yml services
#
# --------------------------------------------------------------------------------------------------

services:

  ## adds NVIDIA GPU support to Jupyterlab service
  jupyterlab:
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: all
               capabilities: [gpu]

# EOF

