# base environment definition without Jupyterlab
# this environment will be cloned to tensorflow and torch
# 2025-09-26

name: base
channels:
  - conda-forge # default repo for miniforge3

dependencies:
  - python=3.12 # make sure we have correct python version
  - pip # package manager
  - pip-tools # other packaging tools

  - pip:

    ## other libraries
    - make # build tools
    - matplotlib # plots library
    - mlflow # powerful mlops suite and experiment runner (library)
    - numpy # advanced library for working with arrays
    - pandas # data manipulation library
    - parquet-tools # commandline parquet viewer
    - polars  # superfast alternative to pandas
    - python-dotenv # managing .env file loading in the runtime context
    - scikit-learn # machine leanring library for python
    - scipy # python scientific library

# EOF

