# base environment for torch (GPU enabled)

name: torch
channels:
  - conda-forge # default repo for miniforge3
  - nvidia   # nvidia packages with cuda to support tensorflow gpu acceleration

dependencies:
  - pip

  - pip:
    - torch>=2.4    # PyTorch, a popular deep learning framework, version 2.4 or higher
    - ipykernel # to make this env appear as kernel
    # for installation of ultralytics yolo you will need libgl1 with apt

# EOF

